Animate selection change
enfluid/apple-scrub-bar pull request #13
Opened 2016-12-21 11:09 UTC by andris-zalitis

2016-12-21 13:31 UTC, andris-zalitis commented
The animation can be seen if checking out branch for this PR: https://github.com/worldslastchance/wlc-calendar/pull/73

2016-12-21 18:18 UTC, rudolf-adamkovic requested changes

2016-12-21 18:18 UTC, salutis commented on SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift
> +func == (lhs: AnimatingMock.EquatableParams, rhs: AnimatingMock.EquatableParams) -> Bool {
Wouldn't `String(describing: lhs) == String(describing: rhs)` be enough?

2016-12-21 18:18 UTC, salutis commented on SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift
> +    static var capturedAnimationsArray: [() -> Void] = []
Consider removing unnecessary type repetition (`Array`)

2016-12-21 18:18 UTC, salutis commented on SlidingSegmentedControlTests/SlidingSegmentedControlTests.swift
> +    static var capturedEquatableParamsArray: [EquatableParams] = []
Consider removing unnecessary type repetition (`Array`) and improving non-descriptive name (`equatableParams`).

2016-12-21 20:31 UTC, andris-zalitis commented
@salutis great points as usual! I've addressed these, ready for review again.

2016-12-22 10:05 UTC, salutis commented
@andris-zalitis What about `capturedConfiguration` or `capturedParameters` instead of `capturedConfigurationParams`?

2016-12-22 10:25 UTC, andris-zalitis commented
@salutis I was just thinking about this morning - "why did I name them params?" 😄

2016-12-22 10:45 UTC, andris-zalitis commented
@salutis 
Ready for review

2016-12-22 10:59 UTC, rudolf-adamkovic approved these changes

2016-12-22 10:59 UTC, merged

2016-12-22 10:59 UTC, salutis commented
@andris-zalitis Top-notch work!

2016-12-22 11:00 UTC, andris-zalitis commented
@salutis Thank you for review and merge!